/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package intellifusion;

public class IF_FACEFEAT {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IF_FACEFEAT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IF_FACEFEAT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IFaceSDKJNI.delete_IF_FACEFEAT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFeature(float[] value) {
    IFaceSDKJNI.IF_FACEFEAT_Feature_set(swigCPtr, this, value);
  }

  public float[] getFeature() {
    return IFaceSDKJNI.IF_FACEFEAT_Feature_get(swigCPtr, this);
  }

  public IF_FACEFEAT() {
    this(IFaceSDKJNI.new_IF_FACEFEAT(), true);
  }

}
