/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package intellifusion;

public final class IF_FacePose {
  public final static IF_FacePose IF_StrictFrontal = new IF_FacePose("IF_StrictFrontal", IFaceSDKJNI.IF_StrictFrontal_get());
  public final static IF_FacePose IF_Frontal = new IF_FacePose("IF_Frontal");
  public final static IF_FacePose IF_HalfLeft = new IF_FacePose("IF_HalfLeft");
  public final static IF_FacePose IF_HalfRight = new IF_FacePose("IF_HalfRight");
  public final static IF_FacePose IF_FullLeft = new IF_FacePose("IF_FullLeft");
  public final static IF_FacePose IF_FullRight = new IF_FacePose("IF_FullRight");
  public final static IF_FacePose IF_FrontalCW30 = new IF_FacePose("IF_FrontalCW30");
  public final static IF_FacePose IF_LeftHalfProfileCW30 = new IF_FacePose("IF_LeftHalfProfileCW30");
  public final static IF_FacePose IF_RightHalfProfileCW30 = new IF_FacePose("IF_RightHalfProfileCW30");
  public final static IF_FacePose IF_LeftProfileCW30 = new IF_FacePose("IF_LeftProfileCW30");
  public final static IF_FacePose IF_RightProfileCW30 = new IF_FacePose("IF_RightProfileCW30");
  public final static IF_FacePose IF_FrontalCCW30 = new IF_FacePose("IF_FrontalCCW30");
  public final static IF_FacePose IF_LeftHalfProfileCCW30 = new IF_FacePose("IF_LeftHalfProfileCCW30");
  public final static IF_FacePose IF_RightHalfProfileCCW30 = new IF_FacePose("IF_RightHalfProfileCCW30");
  public final static IF_FacePose IF_LeftProfileCCW30 = new IF_FacePose("IF_LeftProfileCCW30");
  public final static IF_FacePose IF_RightProfileCCW30 = new IF_FacePose("IF_RightProfileCCW30");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IF_FacePose swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IF_FacePose.class + " with value " + swigValue);
  }

  private IF_FacePose(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IF_FacePose(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IF_FacePose(String swigName, IF_FacePose swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IF_FacePose[] swigValues = { IF_StrictFrontal, IF_Frontal, IF_HalfLeft, IF_HalfRight, IF_FullLeft, IF_FullRight, IF_FrontalCW30, IF_LeftHalfProfileCW30, IF_RightHalfProfileCW30, IF_LeftProfileCW30, IF_RightProfileCW30, IF_FrontalCCW30, IF_LeftHalfProfileCCW30, IF_RightHalfProfileCCW30, IF_LeftProfileCCW30, IF_RightProfileCCW30 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

