/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package intellifusion;

public class if_rect_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected if_rect_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(if_rect_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IFaceSDKJNI.delete_if_rect_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLeft(int value) {
    IFaceSDKJNI.if_rect_t_left_set(swigCPtr, this, value);
  }

  public int getLeft() {
    return IFaceSDKJNI.if_rect_t_left_get(swigCPtr, this);
  }

  public void setTop(int value) {
    IFaceSDKJNI.if_rect_t_top_set(swigCPtr, this, value);
  }

  public int getTop() {
    return IFaceSDKJNI.if_rect_t_top_get(swigCPtr, this);
  }

  public void setRight(int value) {
    IFaceSDKJNI.if_rect_t_right_set(swigCPtr, this, value);
  }

  public int getRight() {
    return IFaceSDKJNI.if_rect_t_right_get(swigCPtr, this);
  }

  public void setBottom(int value) {
    IFaceSDKJNI.if_rect_t_bottom_set(swigCPtr, this, value);
  }

  public int getBottom() {
    return IFaceSDKJNI.if_rect_t_bottom_get(swigCPtr, this);
  }

  public if_rect_t() {
    this(IFaceSDKJNI.new_if_rect_t(), true);
  }

}
