/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package intellifusion;

public class IFaceSDKJNI {
  public final static native int MAX_FACE_COUNT_PER_IMAGE_get();
  public final static native int FEA_LEN_get();
  public final static native double DEFAULT_THRESHOLD_get();
  public final static native void if_rect_t_left_set(long jarg1, if_rect_t jarg1_, int jarg2);
  public final static native int if_rect_t_left_get(long jarg1, if_rect_t jarg1_);
  public final static native void if_rect_t_top_set(long jarg1, if_rect_t jarg1_, int jarg2);
  public final static native int if_rect_t_top_get(long jarg1, if_rect_t jarg1_);
  public final static native void if_rect_t_right_set(long jarg1, if_rect_t jarg1_, int jarg2);
  public final static native int if_rect_t_right_get(long jarg1, if_rect_t jarg1_);
  public final static native void if_rect_t_bottom_set(long jarg1, if_rect_t jarg1_, int jarg2);
  public final static native int if_rect_t_bottom_get(long jarg1, if_rect_t jarg1_);
  public final static native long new_if_rect_t();
  public final static native void delete_if_rect_t(long jarg1);
  public final static native int IF_StrictFrontal_get();
  public final static native void IF_FACERECT_Rect_set(long jarg1, IF_FACERECT jarg1_, long jarg2, if_rect_t jarg2_);
  public final static native long IF_FACERECT_Rect_get(long jarg1, IF_FACERECT jarg1_);
  public final static native void IF_FACERECT_Pose_set(long jarg1, IF_FACERECT jarg1_, int jarg2);
  public final static native int IF_FACERECT_Pose_get(long jarg1, IF_FACERECT jarg1_);
  public final static native void IF_FACERECT_Confidence_set(long jarg1, IF_FACERECT jarg1_, float jarg2);
  public final static native float IF_FACERECT_Confidence_get(long jarg1, IF_FACERECT jarg1_);
  public final static native long new_IF_FACERECT();
  public final static native void delete_IF_FACERECT(long jarg1);
  public final static native void IF_FACEFEAT_Feature_set(long jarg1, IF_FACEFEAT jarg1_, float[] jarg2);
  public final static native float[] IF_FACEFEAT_Feature_get(long jarg1, IF_FACEFEAT jarg1_);
  public final static native long new_IF_FACEFEAT();
  public final static native void delete_IF_FACEFEAT(long jarg1);
  public final static native long new_IfRectArray(int jarg1);
  public final static native void delete_IfRectArray(long jarg1);
  public final static native long IfRectArray_getitem(long jarg1, IfRectArray jarg1_, int jarg2);
  public final static native void IfRectArray_setitem(long jarg1, IfRectArray jarg1_, int jarg2, long jarg3, IF_FACERECT jarg3_);
  public final static native long IfRectArray_cast(long jarg1, IfRectArray jarg1_);
  public final static native long IfRectArray_frompointer(long jarg1, IF_FACERECT jarg1_);
  public final static native long new_IfFeatArray(int jarg1);
  public final static native void delete_IfFeatArray(long jarg1);
  public final static native long IfFeatArray_getitem(long jarg1, IfFeatArray jarg1_, int jarg2);
  public final static native void IfFeatArray_setitem(long jarg1, IfFeatArray jarg1_, int jarg2, long jarg3, IF_FACEFEAT jarg3_);
  public final static native long IfFeatArray_cast(long jarg1, IfFeatArray jarg1_);
  public final static native long IfFeatArray_frompointer(long jarg1, IF_FACEFEAT jarg1_);
  public final static native long face_detect_create_instance();
  public final static native void face_detect_release_instance(long jarg1);
  public final static native long face_verify_create_instance();
  public final static native long face_verify_duplicate_instance_with_prefix(String jarg1, long jarg2);
  public final static native void face_verify_release_instance(long jarg1);
  public final static native int face_detect_and_feature_extract(long jarg1, long jarg2, String jarg3, long jarg4, IF_FACERECT jarg4_, long jarg5, IF_FACEFEAT jarg5_);
  public final static native int face_verify_pca_feature(long jarg1, long jarg2, IF_FACEFEAT jarg2_, long jarg3, IF_FACEFEAT jarg3_, float[] jarg4);
}
