/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package intellifusion;

public class IFaceSDK implements IFaceSDKConstants {
  public static SWIGTYPE_p_void face_detect_create_instance() {
    long cPtr = IFaceSDKJNI.face_detect_create_instance();
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void face_detect_release_instance(SWIGTYPE_p_void fd_inst) {
    IFaceSDKJNI.face_detect_release_instance(SWIGTYPE_p_void.getCPtr(fd_inst));
  }

  public static SWIGTYPE_p_void face_verify_create_instance() {
    long cPtr = IFaceSDKJNI.face_verify_create_instance();
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void face_verify_duplicate_instance_with_prefix(String path, SWIGTYPE_p_void vinst) {
    long cPtr = IFaceSDKJNI.face_verify_duplicate_instance_with_prefix(path, SWIGTYPE_p_void.getCPtr(vinst));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void face_verify_release_instance(SWIGTYPE_p_void fv_inst) {
    IFaceSDKJNI.face_verify_release_instance(SWIGTYPE_p_void.getCPtr(fv_inst));
  }

  public static int face_detect_and_feature_extract(SWIGTYPE_p_void fd_inst, SWIGTYPE_p_void fv_inst, String inputImgName, IF_FACERECT face_rect_array, IF_FACEFEAT face_feat_array) {
    return IFaceSDKJNI.face_detect_and_feature_extract(SWIGTYPE_p_void.getCPtr(fd_inst), SWIGTYPE_p_void.getCPtr(fv_inst), inputImgName, IF_FACERECT.getCPtr(face_rect_array), face_rect_array, IF_FACEFEAT.getCPtr(face_feat_array), face_feat_array);
  }

  public static int face_verify_pca_feature(SWIGTYPE_p_void fv_inst, IF_FACEFEAT feat1, IF_FACEFEAT feat2, float[] OUTPUT) {
    return IFaceSDKJNI.face_verify_pca_feature(SWIGTYPE_p_void.getCPtr(fv_inst), IF_FACEFEAT.getCPtr(feat1), feat1, IF_FACEFEAT.getCPtr(feat2), feat2, OUTPUT);
  }

}
