/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package intellifusion;

public interface IFaceSDKConstants {
  public final static int MAX_FACE_COUNT_PER_IMAGE = IFaceSDKJNI.MAX_FACE_COUNT_PER_IMAGE_get();
  public final static int FEA_LEN = IFaceSDKJNI.FEA_LEN_get();
  public final static double DEFAULT_THRESHOLD = IFaceSDKJNI.DEFAULT_THRESHOLD_get();
}
