/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package intellifusion;

public class IfFeatArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IfFeatArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IfFeatArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IFaceSDKJNI.delete_IfFeatArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IfFeatArray(int nelements) {
    this(IFaceSDKJNI.new_IfFeatArray(nelements), true);
  }

  public IF_FACEFEAT getitem(int index) {
    return new IF_FACEFEAT(IFaceSDKJNI.IfFeatArray_getitem(swigCPtr, this, index), true);
  }

  public void setitem(int index, IF_FACEFEAT value) {
    IFaceSDKJNI.IfFeatArray_setitem(swigCPtr, this, index, IF_FACEFEAT.getCPtr(value), value);
  }

  public IF_FACEFEAT cast() {
    long cPtr = IFaceSDKJNI.IfFeatArray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new IF_FACEFEAT(cPtr, false);
  }

  public static IfFeatArray frompointer(IF_FACEFEAT t) {
    long cPtr = IFaceSDKJNI.IfFeatArray_frompointer(IF_FACEFEAT.getCPtr(t), t);
    return (cPtr == 0) ? null : new IfFeatArray(cPtr, false);
  }

}
