/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package intellifusion;

public class IfRectArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IfRectArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IfRectArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IFaceSDKJNI.delete_IfRectArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IfRectArray(int nelements) {
    this(IFaceSDKJNI.new_IfRectArray(nelements), true);
  }

  public IF_FACERECT getitem(int index) {
    return new IF_FACERECT(IFaceSDKJNI.IfRectArray_getitem(swigCPtr, this, index), true);
  }

  public void setitem(int index, IF_FACERECT value) {
    IFaceSDKJNI.IfRectArray_setitem(swigCPtr, this, index, IF_FACERECT.getCPtr(value), value);
  }

  public IF_FACERECT cast() {
    long cPtr = IFaceSDKJNI.IfRectArray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new IF_FACERECT(cPtr, false);
  }

  public static IfRectArray frompointer(IF_FACERECT t) {
    long cPtr = IFaceSDKJNI.IfRectArray_frompointer(IF_FACERECT.getCPtr(t), t);
    return (cPtr == 0) ? null : new IfRectArray(cPtr, false);
  }

}
