/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum E_FACE_EXTRACT_TYPE implements org.apache.thrift.TEnum {
  FACE_EXT_TYPE_BLACKDETAIL(0),
  FACE_EXT_TYPE_SUSPECTDETAIL(1),
  FACE_EXT_TYPE_REDDETAIL(2),
  FACE_EXT_TYPE_CIDDETAIL(3),
  FACE_EXT_TYPE_JUNZHUDETAIL(4),
  FACE_EXT_TYPE_FACEINFO(5),
  FACE_EXT_TYPE_OTHERDETAIL(6),
  FACE_EXT_TYPE_FAKEDETAIL(7);

  private final int value;

  private E_FACE_EXTRACT_TYPE(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static E_FACE_EXTRACT_TYPE findByValue(int value) { 
    switch (value) {
      case 0:
        return FACE_EXT_TYPE_BLACKDETAIL;
      case 1:
        return FACE_EXT_TYPE_SUSPECTDETAIL;
      case 2:
        return FACE_EXT_TYPE_REDDETAIL;
      case 3:
        return FACE_EXT_TYPE_CIDDETAIL;
      case 4:
        return FACE_EXT_TYPE_JUNZHUDETAIL;
      case 5:
        return FACE_EXT_TYPE_FACEINFO;
      case 6:
        return FACE_EXT_TYPE_OTHERDETAIL;
      case 7:
        return FACE_EXT_TYPE_FAKEDETAIL;
      default:
        return null;
    }
  }
}
