/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum E_FLUSH_PROGRESS_TYPE implements org.apache.thrift.TEnum {
  FLUSH_PROGRESS_TYPE_CIDDETAIL(0),
  FLUSH_PROGRESS_TYPE_BLACKDETAIL(1),
  FLUSH_PROGRESS_TYPE_FACEFEATURE(2),
  FLUSH_PROGRESS_TYPE_JUZHUDETAIL(3),
  FLUSH_PROGRESS_TYPE_OHTERDETAIL(4);

  private final int value;

  private E_FLUSH_PROGRESS_TYPE(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static E_FLUSH_PROGRESS_TYPE findByValue(int value) { 
    switch (value) {
      case 0:
        return FLUSH_PROGRESS_TYPE_CIDDETAIL;
      case 1:
        return FLUSH_PROGRESS_TYPE_BLACKDETAIL;
      case 2:
        return FLUSH_PROGRESS_TYPE_FACEFEATURE;
      case 3:
        return FLUSH_PROGRESS_TYPE_JUZHUDETAIL;
      case 4:
        return FLUSH_PROGRESS_TYPE_OHTERDETAIL;
      default:
        return null;
    }
  }
}
