/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EBListIoctrlType implements org.apache.thrift.TEnum {
  BLIST_IOCTRL_CAMERA_UPDATE(0),
  BLIST_IOCTRL_AREA_UPDATE(1),
  BLIST_IOCTRL_BLACK_PERSON_UPDATE(2);

  private final int value;

  private EBListIoctrlType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EBListIoctrlType findByValue(int value) { 
    switch (value) {
      case 0:
        return BLIST_IOCTRL_CAMERA_UPDATE;
      case 1:
        return BLIST_IOCTRL_AREA_UPDATE;
      case 2:
        return BLIST_IOCTRL_BLACK_PERSON_UPDATE;
      default:
        return null;
    }
  }
}
