/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ECameraIoctrlType implements org.apache.thrift.TEnum {
  CAMERA_IOCTRL_CAPTURE(0);

  private final int value;

  private ECameraIoctrlType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ECameraIoctrlType findByValue(int value) { 
    switch (value) {
      case 0:
        return CAMERA_IOCTRL_CAPTURE;
      default:
        return null;
    }
  }
}
