/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EEnginIoctrlType implements org.apache.thrift.TEnum {
  ENGIN_IOCTRL_TRACE(1953653091),
  ENGIN_IOCTRL_DUMP(1691706480),
  ENGIN_IOCTRL_IOCTRL(1668575852),
  ENGIN_IOCTRL_SURVEIL(1937076854);

  private final int value;

  private EEnginIoctrlType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EEnginIoctrlType findByValue(int value) { 
    switch (value) {
      case 1953653091:
        return ENGIN_IOCTRL_TRACE;
      case 1691706480:
        return ENGIN_IOCTRL_DUMP;
      case 1668575852:
        return ENGIN_IOCTRL_IOCTRL;
      case 1937076854:
        return ENGIN_IOCTRL_SURVEIL;
      default:
        return null;
    }
  }
}
