/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EFaceAttrUpdateAction implements org.apache.thrift.TEnum {
  ATTR_UPDATE_ACTION_STARTUP(0),
  ATTR_UPDATE_ACTION_STOP(1);

  private final int value;

  private EFaceAttrUpdateAction(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EFaceAttrUpdateAction findByValue(int value) { 
    switch (value) {
      case 0:
        return ATTR_UPDATE_ACTION_STARTUP;
      case 1:
        return ATTR_UPDATE_ACTION_STOP;
      default:
        return null;
    }
  }
}
