/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EFakeFilterUpdateType implements org.apache.thrift.TEnum {
  FILTER_UPDATE_ALL(0),
  FILTER_UPDATE_FACE(1),
  FILTER_UPDATE_SRC(2);

  private final int value;

  private EFakeFilterUpdateType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EFakeFilterUpdateType findByValue(int value) { 
    switch (value) {
      case 0:
        return FILTER_UPDATE_ALL;
      case 1:
        return FILTER_UPDATE_FACE;
      case 2:
        return FILTER_UPDATE_SRC;
      default:
        return null;
    }
  }
}
