/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EFeatureAlgVersion implements org.apache.thrift.TEnum {
  FEATURE_ALG_VERSION_ORG(0),
  FEATURE_ALG_VERSION_TUNA(1),
  FEATURE_ALG_VERSION_RABBIT(2),
  FEATURE_ALG_VERSION_TORTOISE(3);

  private final int value;

  private EFeatureAlgVersion(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EFeatureAlgVersion findByValue(int value) { 
    switch (value) {
      case 0:
        return FEATURE_ALG_VERSION_ORG;
      case 1:
        return FEATURE_ALG_VERSION_TUNA;
      case 2:
        return FEATURE_ALG_VERSION_RABBIT;
      case 3:
        return FEATURE_ALG_VERSION_TORTOISE;
      default:
        return null;
    }
  }
}
