/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ELongTermFiltCtrl implements org.apache.thrift.TEnum {
  LONG_FILT_CTRL_INIT(0),
  LONG_FILT_CTRL_UPDATE(1),
  LONG_FILT_CTRL_ADD_PERSON(2),
  LONG_FILT_CTRL_DEL_PERSON(3),
  LONG_FILT_CTRL_ADD_CAMERA(4),
  LONG_FILT_CTRL_DEL_CAMERA(5),
  LONG_FILT_CTRL_CLR_ZONE(6);

  private final int value;

  private ELongTermFiltCtrl(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ELongTermFiltCtrl findByValue(int value) { 
    switch (value) {
      case 0:
        return LONG_FILT_CTRL_INIT;
      case 1:
        return LONG_FILT_CTRL_UPDATE;
      case 2:
        return LONG_FILT_CTRL_ADD_PERSON;
      case 3:
        return LONG_FILT_CTRL_DEL_PERSON;
      case 4:
        return LONG_FILT_CTRL_ADD_CAMERA;
      case 5:
        return LONG_FILT_CTRL_DEL_CAMERA;
      case 6:
        return LONG_FILT_CTRL_CLR_ZONE;
      default:
        return null;
    }
  }
}
