/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EPersonIoctrlType implements org.apache.thrift.TEnum {
  PERSON_IOCTRL_RULEIID(0);

  private final int value;

  private EPersonIoctrlType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EPersonIoctrlType findByValue(int value) { 
    switch (value) {
      case 0:
        return PERSON_IOCTRL_RULEIID;
      default:
        return null;
    }
  }
}
