/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ERedListIoctrlType implements org.apache.thrift.TEnum {
  REDLIST_IOCTRL_QUERY(0),
  REDLIST_IOCTRL_ADD(1),
  REDLIST_IOCTRL_DEL(2),
  REDLIST_IOCTRL_REFRESH(3),
  REDLIST_IOCTRL_SWITCHON(4),
  REDLIST_IOCTRL_SWITCHOFF(5);

  private final int value;

  private ERedListIoctrlType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ERedListIoctrlType findByValue(int value) { 
    switch (value) {
      case 0:
        return REDLIST_IOCTRL_QUERY;
      case 1:
        return REDLIST_IOCTRL_ADD;
      case 2:
        return REDLIST_IOCTRL_DEL;
      case 3:
        return REDLIST_IOCTRL_REFRESH;
      case 4:
        return REDLIST_IOCTRL_SWITCHON;
      case 5:
        return REDLIST_IOCTRL_SWITCHOFF;
      default:
        return null;
    }
  }
}
