/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ESnaperCtrlType implements org.apache.thrift.TEnum {
  SNAPER_CTRL_IPC_CAP(0),
  SNAPER_CTRL_IPC_RST(1);

  private final int value;

  private ESnaperCtrlType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ESnaperCtrlType findByValue(int value) { 
    switch (value) {
      case 0:
        return SNAPER_CTRL_IPC_CAP;
      case 1:
        return SNAPER_CTRL_IPC_RST;
      default:
        return null;
    }
  }
}
