/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ESurveilIoctrlType implements org.apache.thrift.TEnum {
  SURVEIL_IOCTRL_ADD_PERSON(0),
  SURVEIL_IOCTRL_DEL_PERSON(1),
  SURVEIL_IOCTRL_UPDATE_PERSON(2);

  private final int value;

  private ESurveilIoctrlType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ESurveilIoctrlType findByValue(int value) { 
    switch (value) {
      case 0:
        return SURVEIL_IOCTRL_ADD_PERSON;
      case 1:
        return SURVEIL_IOCTRL_DEL_PERSON;
      case 2:
        return SURVEIL_IOCTRL_UPDATE_PERSON;
      default:
        return null;
    }
  }
}
