/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ETaskIoctrlType implements org.apache.thrift.TEnum {
  TASK_IOCTRL_BANKID(0),
  TASK_IOCTRL_SOURCEID(1),
  TASK_IOCTRL_TYPE(2);

  private final int value;

  private ETaskIoctrlType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ETaskIoctrlType findByValue(int value) { 
    switch (value) {
      case 0:
        return TASK_IOCTRL_BANKID;
      case 1:
        return TASK_IOCTRL_SOURCEID;
      case 2:
        return TASK_IOCTRL_TYPE;
      default:
        return null;
    }
  }
}
