/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ETraceIoctrlType implements org.apache.thrift.TEnum {
  TRACE_IOCTRL_LEVEL(0),
  TRACE_IOCTRL_SWITCH(1);

  private final int value;

  private ETraceIoctrlType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ETraceIoctrlType findByValue(int value) { 
    switch (value) {
      case 0:
        return TRACE_IOCTRL_LEVEL;
      case 1:
        return TRACE_IOCTRL_SWITCH;
      default:
        return null;
    }
  }
}
