/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2017-8-31")
public class T_CapRstOndemand implements org.apache.thrift.TBase<T_CapRstOndemand, T_CapRstOndemand._Fields>, java.io.Serializable, Cloneable, Comparable<T_CapRstOndemand> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("T_CapRstOndemand");

  private static final org.apache.thrift.protocol.TField IMAGE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("ImageId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField FACE_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("FaceIds", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new T_CapRstOndemandStandardSchemeFactory());
    schemes.put(TupleScheme.class, new T_CapRstOndemandTupleSchemeFactory());
  }

  public long ImageId; // required
  public List<Long> FaceIds; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    IMAGE_ID((short)1, "ImageId"),
    FACE_IDS((short)2, "FaceIds");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // IMAGE_ID
          return IMAGE_ID;
        case 2: // FACE_IDS
          return FACE_IDS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __IMAGEID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.IMAGE_ID, new org.apache.thrift.meta_data.FieldMetaData("ImageId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.FACE_IDS, new org.apache.thrift.meta_data.FieldMetaData("FaceIds", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(T_CapRstOndemand.class, metaDataMap);
  }

  public T_CapRstOndemand() {
  }

  public T_CapRstOndemand(
    long ImageId,
    List<Long> FaceIds)
  {
    this();
    this.ImageId = ImageId;
    setImageIdIsSet(true);
    this.FaceIds = FaceIds;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public T_CapRstOndemand(T_CapRstOndemand other) {
    __isset_bitfield = other.__isset_bitfield;
    this.ImageId = other.ImageId;
    if (other.isSetFaceIds()) {
      List<Long> __this__FaceIds = new ArrayList<Long>(other.FaceIds);
      this.FaceIds = __this__FaceIds;
    }
  }

  public T_CapRstOndemand deepCopy() {
    return new T_CapRstOndemand(this);
  }

  @Override
  public void clear() {
    setImageIdIsSet(false);
    this.ImageId = 0;
    this.FaceIds = null;
  }

  public long getImageId() {
    return this.ImageId;
  }

  public T_CapRstOndemand setImageId(long ImageId) {
    this.ImageId = ImageId;
    setImageIdIsSet(true);
    return this;
  }

  public void unsetImageId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __IMAGEID_ISSET_ID);
  }

  /** Returns true if field ImageId is set (has been assigned a value) and false otherwise */
  public boolean isSetImageId() {
    return EncodingUtils.testBit(__isset_bitfield, __IMAGEID_ISSET_ID);
  }

  public void setImageIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __IMAGEID_ISSET_ID, value);
  }

  public int getFaceIdsSize() {
    return (this.FaceIds == null) ? 0 : this.FaceIds.size();
  }

  public java.util.Iterator<Long> getFaceIdsIterator() {
    return (this.FaceIds == null) ? null : this.FaceIds.iterator();
  }

  public void addToFaceIds(long elem) {
    if (this.FaceIds == null) {
      this.FaceIds = new ArrayList<Long>();
    }
    this.FaceIds.add(elem);
  }

  public List<Long> getFaceIds() {
    return this.FaceIds;
  }

  public T_CapRstOndemand setFaceIds(List<Long> FaceIds) {
    this.FaceIds = FaceIds;
    return this;
  }

  public void unsetFaceIds() {
    this.FaceIds = null;
  }

  /** Returns true if field FaceIds is set (has been assigned a value) and false otherwise */
  public boolean isSetFaceIds() {
    return this.FaceIds != null;
  }

  public void setFaceIdsIsSet(boolean value) {
    if (!value) {
      this.FaceIds = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case IMAGE_ID:
      if (value == null) {
        unsetImageId();
      } else {
        setImageId((Long)value);
      }
      break;

    case FACE_IDS:
      if (value == null) {
        unsetFaceIds();
      } else {
        setFaceIds((List<Long>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case IMAGE_ID:
      return Long.valueOf(getImageId());

    case FACE_IDS:
      return getFaceIds();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case IMAGE_ID:
      return isSetImageId();
    case FACE_IDS:
      return isSetFaceIds();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof T_CapRstOndemand)
      return this.equals((T_CapRstOndemand)that);
    return false;
  }

  public boolean equals(T_CapRstOndemand that) {
    if (that == null)
      return false;

    boolean this_present_ImageId = true;
    boolean that_present_ImageId = true;
    if (this_present_ImageId || that_present_ImageId) {
      if (!(this_present_ImageId && that_present_ImageId))
        return false;
      if (this.ImageId != that.ImageId)
        return false;
    }

    boolean this_present_FaceIds = true && this.isSetFaceIds();
    boolean that_present_FaceIds = true && that.isSetFaceIds();
    if (this_present_FaceIds || that_present_FaceIds) {
      if (!(this_present_FaceIds && that_present_FaceIds))
        return false;
      if (!this.FaceIds.equals(that.FaceIds))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_ImageId = true;
    list.add(present_ImageId);
    if (present_ImageId)
      list.add(ImageId);

    boolean present_FaceIds = true && (isSetFaceIds());
    list.add(present_FaceIds);
    if (present_FaceIds)
      list.add(FaceIds);

    return list.hashCode();
  }

  @Override
  public int compareTo(T_CapRstOndemand other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetImageId()).compareTo(other.isSetImageId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImageId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ImageId, other.ImageId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFaceIds()).compareTo(other.isSetFaceIds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFaceIds()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.FaceIds, other.FaceIds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("T_CapRstOndemand(");
    boolean first = true;

    sb.append("ImageId:");
    sb.append(this.ImageId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("FaceIds:");
    if (this.FaceIds == null) {
      sb.append("null");
    } else {
      sb.append(this.FaceIds);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class T_CapRstOndemandStandardSchemeFactory implements SchemeFactory {
    public T_CapRstOndemandStandardScheme getScheme() {
      return new T_CapRstOndemandStandardScheme();
    }
  }

  private static class T_CapRstOndemandStandardScheme extends StandardScheme<T_CapRstOndemand> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, T_CapRstOndemand struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // IMAGE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.ImageId = iprot.readI64();
              struct.setImageIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FACE_IDS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.FaceIds = new ArrayList<Long>(_list0.size);
                long _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = iprot.readI64();
                  struct.FaceIds.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setFaceIdsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, T_CapRstOndemand struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(IMAGE_ID_FIELD_DESC);
      oprot.writeI64(struct.ImageId);
      oprot.writeFieldEnd();
      if (struct.FaceIds != null) {
        oprot.writeFieldBegin(FACE_IDS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, struct.FaceIds.size()));
          for (long _iter3 : struct.FaceIds)
          {
            oprot.writeI64(_iter3);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class T_CapRstOndemandTupleSchemeFactory implements SchemeFactory {
    public T_CapRstOndemandTupleScheme getScheme() {
      return new T_CapRstOndemandTupleScheme();
    }
  }

  private static class T_CapRstOndemandTupleScheme extends TupleScheme<T_CapRstOndemand> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, T_CapRstOndemand struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetImageId()) {
        optionals.set(0);
      }
      if (struct.isSetFaceIds()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetImageId()) {
        oprot.writeI64(struct.ImageId);
      }
      if (struct.isSetFaceIds()) {
        {
          oprot.writeI32(struct.FaceIds.size());
          for (long _iter4 : struct.FaceIds)
          {
            oprot.writeI64(_iter4);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, T_CapRstOndemand struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.ImageId = iprot.readI64();
        struct.setImageIdIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, iprot.readI32());
          struct.FaceIds = new ArrayList<Long>(_list5.size);
          long _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = iprot.readI64();
            struct.FaceIds.add(_elem6);
          }
        }
        struct.setFaceIdsIsSet(true);
      }
    }
  }

}

