/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum T_IF_FacePose implements org.apache.thrift.TEnum {
  IF_StrictFrontal(0),
  IF_Frontal(1),
  IF_HalfLeft(2),
  IF_HalfRight(3),
  IF_FullLeft(4),
  IF_FullRight(5),
  IF_FrontalCW30(6),
  IF_LeftHalfProfileCW30(7),
  IF_RightHalfProfileCW30(8),
  IF_LeftProfileCW30(9),
  IF_RightProfileCW30(10),
  IF_FrontalCCW30(11),
  IF_LeftHalfProfileCCW30(12),
  IF_RightHalfProfileCCW30(13),
  IF_LeftProfileCCW30(14),
  IF_RightProfileCCW30(15);

  private final int value;

  private T_IF_FacePose(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static T_IF_FacePose findByValue(int value) { 
    switch (value) {
      case 0:
        return IF_StrictFrontal;
      case 1:
        return IF_Frontal;
      case 2:
        return IF_HalfLeft;
      case 3:
        return IF_HalfRight;
      case 4:
        return IF_FullLeft;
      case 5:
        return IF_FullRight;
      case 6:
        return IF_FrontalCW30;
      case 7:
        return IF_LeftHalfProfileCW30;
      case 8:
        return IF_RightHalfProfileCW30;
      case 9:
        return IF_LeftProfileCW30;
      case 10:
        return IF_RightProfileCW30;
      case 11:
        return IF_FrontalCCW30;
      case 12:
        return IF_LeftHalfProfileCCW30;
      case 13:
        return IF_RightHalfProfileCCW30;
      case 14:
        return IF_LeftProfileCCW30;
      case 15:
        return IF_RightProfileCCW30;
      default:
        return null;
    }
  }
}
