/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package intellif.ifaas;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2017-8-31")
public class T_IF_FACERECT implements org.apache.thrift.TBase<T_IF_FACERECT, T_IF_FACERECT._Fields>, java.io.Serializable, Cloneable, Comparable<T_IF_FACERECT> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("T_IF_FACERECT");

  private static final org.apache.thrift.protocol.TField RECT_FIELD_DESC = new org.apache.thrift.protocol.TField("Rect", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField POSE_FIELD_DESC = new org.apache.thrift.protocol.TField("Pose", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField FORBIDEN_FIELD_DESC = new org.apache.thrift.protocol.TField("forbiden", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new T_IF_FACERECTStandardSchemeFactory());
    schemes.put(TupleScheme.class, new T_IF_FACERECTTupleSchemeFactory());
  }

  public t_if_rect_t Rect; // required
  /**
   * 
   * @see T_IF_FacePose
   */
  public T_IF_FacePose Pose; // required
  public int forbiden; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RECT((short)1, "Rect"),
    /**
     * 
     * @see T_IF_FacePose
     */
    POSE((short)2, "Pose"),
    FORBIDEN((short)3, "forbiden");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RECT
          return RECT;
        case 2: // POSE
          return POSE;
        case 3: // FORBIDEN
          return FORBIDEN;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __FORBIDEN_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RECT, new org.apache.thrift.meta_data.FieldMetaData("Rect", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, t_if_rect_t.class)));
    tmpMap.put(_Fields.POSE, new org.apache.thrift.meta_data.FieldMetaData("Pose", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, T_IF_FacePose.class)));
    tmpMap.put(_Fields.FORBIDEN, new org.apache.thrift.meta_data.FieldMetaData("forbiden", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(T_IF_FACERECT.class, metaDataMap);
  }

  public T_IF_FACERECT() {
  }

  public T_IF_FACERECT(
    t_if_rect_t Rect,
    T_IF_FacePose Pose,
    int forbiden)
  {
    this();
    this.Rect = Rect;
    this.Pose = Pose;
    this.forbiden = forbiden;
    setForbidenIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public T_IF_FACERECT(T_IF_FACERECT other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetRect()) {
      this.Rect = new t_if_rect_t(other.Rect);
    }
    if (other.isSetPose()) {
      this.Pose = other.Pose;
    }
    this.forbiden = other.forbiden;
  }

  public T_IF_FACERECT deepCopy() {
    return new T_IF_FACERECT(this);
  }

  @Override
  public void clear() {
    this.Rect = null;
    this.Pose = null;
    setForbidenIsSet(false);
    this.forbiden = 0;
  }

  public t_if_rect_t getRect() {
    return this.Rect;
  }

  public T_IF_FACERECT setRect(t_if_rect_t Rect) {
    this.Rect = Rect;
    return this;
  }

  public void unsetRect() {
    this.Rect = null;
  }

  /** Returns true if field Rect is set (has been assigned a value) and false otherwise */
  public boolean isSetRect() {
    return this.Rect != null;
  }

  public void setRectIsSet(boolean value) {
    if (!value) {
      this.Rect = null;
    }
  }

  /**
   * 
   * @see T_IF_FacePose
   */
  public T_IF_FacePose getPose() {
    return this.Pose;
  }

  /**
   * 
   * @see T_IF_FacePose
   */
  public T_IF_FACERECT setPose(T_IF_FacePose Pose) {
    this.Pose = Pose;
    return this;
  }

  public void unsetPose() {
    this.Pose = null;
  }

  /** Returns true if field Pose is set (has been assigned a value) and false otherwise */
  public boolean isSetPose() {
    return this.Pose != null;
  }

  public void setPoseIsSet(boolean value) {
    if (!value) {
      this.Pose = null;
    }
  }

  public int getForbiden() {
    return this.forbiden;
  }

  public T_IF_FACERECT setForbiden(int forbiden) {
    this.forbiden = forbiden;
    setForbidenIsSet(true);
    return this;
  }

  public void unsetForbiden() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FORBIDEN_ISSET_ID);
  }

  /** Returns true if field forbiden is set (has been assigned a value) and false otherwise */
  public boolean isSetForbiden() {
    return EncodingUtils.testBit(__isset_bitfield, __FORBIDEN_ISSET_ID);
  }

  public void setForbidenIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FORBIDEN_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RECT:
      if (value == null) {
        unsetRect();
      } else {
        setRect((t_if_rect_t)value);
      }
      break;

    case POSE:
      if (value == null) {
        unsetPose();
      } else {
        setPose((T_IF_FacePose)value);
      }
      break;

    case FORBIDEN:
      if (value == null) {
        unsetForbiden();
      } else {
        setForbiden((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RECT:
      return getRect();

    case POSE:
      return getPose();

    case FORBIDEN:
      return Integer.valueOf(getForbiden());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RECT:
      return isSetRect();
    case POSE:
      return isSetPose();
    case FORBIDEN:
      return isSetForbiden();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof T_IF_FACERECT)
      return this.equals((T_IF_FACERECT)that);
    return false;
  }

  public boolean equals(T_IF_FACERECT that) {
    if (that == null)
      return false;

    boolean this_present_Rect = true && this.isSetRect();
    boolean that_present_Rect = true && that.isSetRect();
    if (this_present_Rect || that_present_Rect) {
      if (!(this_present_Rect && that_present_Rect))
        return false;
      if (!this.Rect.equals(that.Rect))
        return false;
    }

    boolean this_present_Pose = true && this.isSetPose();
    boolean that_present_Pose = true && that.isSetPose();
    if (this_present_Pose || that_present_Pose) {
      if (!(this_present_Pose && that_present_Pose))
        return false;
      if (!this.Pose.equals(that.Pose))
        return false;
    }

    boolean this_present_forbiden = true;
    boolean that_present_forbiden = true;
    if (this_present_forbiden || that_present_forbiden) {
      if (!(this_present_forbiden && that_present_forbiden))
        return false;
      if (this.forbiden != that.forbiden)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_Rect = true && (isSetRect());
    list.add(present_Rect);
    if (present_Rect)
      list.add(Rect);

    boolean present_Pose = true && (isSetPose());
    list.add(present_Pose);
    if (present_Pose)
      list.add(Pose.getValue());

    boolean present_forbiden = true;
    list.add(present_forbiden);
    if (present_forbiden)
      list.add(forbiden);

    return list.hashCode();
  }

  @Override
  public int compareTo(T_IF_FACERECT other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetRect()).compareTo(other.isSetRect());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRect()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Rect, other.Rect);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPose()).compareTo(other.isSetPose());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPose()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Pose, other.Pose);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetForbiden()).compareTo(other.isSetForbiden());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetForbiden()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.forbiden, other.forbiden);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("T_IF_FACERECT(");
    boolean first = true;

    sb.append("Rect:");
    if (this.Rect == null) {
      sb.append("null");
    } else {
      sb.append(this.Rect);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("Pose:");
    if (this.Pose == null) {
      sb.append("null");
    } else {
      sb.append(this.Pose);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("forbiden:");
    sb.append(this.forbiden);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (Rect != null) {
      Rect.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class T_IF_FACERECTStandardSchemeFactory implements SchemeFactory {
    public T_IF_FACERECTStandardScheme getScheme() {
      return new T_IF_FACERECTStandardScheme();
    }
  }

  private static class T_IF_FACERECTStandardScheme extends StandardScheme<T_IF_FACERECT> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, T_IF_FACERECT struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RECT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.Rect = new t_if_rect_t();
              struct.Rect.read(iprot);
              struct.setRectIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // POSE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.Pose = intellif.ifaas.T_IF_FacePose.findByValue(iprot.readI32());
              struct.setPoseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // FORBIDEN
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.forbiden = iprot.readI32();
              struct.setForbidenIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, T_IF_FACERECT struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.Rect != null) {
        oprot.writeFieldBegin(RECT_FIELD_DESC);
        struct.Rect.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.Pose != null) {
        oprot.writeFieldBegin(POSE_FIELD_DESC);
        oprot.writeI32(struct.Pose.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(FORBIDEN_FIELD_DESC);
      oprot.writeI32(struct.forbiden);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class T_IF_FACERECTTupleSchemeFactory implements SchemeFactory {
    public T_IF_FACERECTTupleScheme getScheme() {
      return new T_IF_FACERECTTupleScheme();
    }
  }

  private static class T_IF_FACERECTTupleScheme extends TupleScheme<T_IF_FACERECT> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, T_IF_FACERECT struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetRect()) {
        optionals.set(0);
      }
      if (struct.isSetPose()) {
        optionals.set(1);
      }
      if (struct.isSetForbiden()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetRect()) {
        struct.Rect.write(oprot);
      }
      if (struct.isSetPose()) {
        oprot.writeI32(struct.Pose.getValue());
      }
      if (struct.isSetForbiden()) {
        oprot.writeI32(struct.forbiden);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, T_IF_FACERECT struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.Rect = new t_if_rect_t();
        struct.Rect.read(iprot);
        struct.setRectIsSet(true);
      }
      if (incoming.get(1)) {
        struct.Pose = intellif.ifaas.T_IF_FacePose.findByValue(iprot.readI32());
        struct.setPoseIsSet(true);
      }
      if (incoming.get(2)) {
        struct.forbiden = iprot.readI32();
        struct.setForbidenIsSet(true);
      }
    }
  }

}

