
CREATE TABLE IF NOT EXISTS cm_t_user(
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键'
  , username VARCHAR(40) NOT NULL COMMENT '用户名'
  , password VARCHAR(256) NOT NULL COMMENT '密码'
  , nickname VARCHAR(40) NOT NULL COMMENT '昵称'
  , modify_time DATETIME NOT NULL COMMENT '修改时间'
  , modifier_id BIGINT(20) NOT NULL COMMENT '修改人员'
  , modifier_name VARCHAR(40) NOT NULL COMMENT '修改人员'
  ,PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=UTF8;

